# Preâmbulo Geral
project:
  type: book
  output-dir: docs

book:
  title: "**Curso: Agente de Fiscalização de Trânsito**"
  subtitle: "**Disciplina: Papel Educador do Agente**"
  date: "08/21/2025"
  author:
    name: Mário Diego Rocha Valente
    orcid: 0000-0001-7262-3336
    corresponding: TRUE
    affiliation:
        name: ANALISTA DE TRÂNSITO/DETRAN-PA
        url: mariovalente@detran.pa.gov.br
  page-footer:
    left: |
      Was Written by (**VALENTE, M.D.R - 2025**).
    right: |
      DETRAN-PA.
  cover-image: CAPA.png
  favicon: CAPA.png
  repo-url: https://github.com/MarioDhiego
  repo-subdir: book
  repo-branch: main           # master
  repo-actions: [edit, issue, source]
  sharing: [twitter, linkedin]
  downloads: [pdf, docx]
  page-navigation: TRUE
  reader-mode: TRUE
  sidebar:
        search: TRUE
  chapters:
    - index.qmd
    - baselegal.qmd
    - Introducao.qmd
    - Capitulo2.qmd
    - Capitulo3.qmd
    - Referencias.qmd
bibliography: references.bib
format:
  html:
    toc-title: SUMÁRIO
    toc-location: right
    number-sections: TRUE
    theme:
      light: cosmo
      dark:  superhero
    code-fold: TRUE
    code-tools: TRUE
    code-link: TRUE

