
```{=html}
<style>
  body{text-align: justify}
</style>
```

::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::


# **Técnicas de Abordagem**
## **Planejamento da Abordagem**

-   Antes de cada ação o coordenador deverá reunir-se com a equipe e parceiros para detalhar a forma de trabalho;

-   Deverá ser atribuído as tarefas e dividir as funções para cada membro da equipe;

-   Identificar os parceiros e a atuação de cada um no momento da abordagem;

-   Comunicar a linguagem que será utilizada durante a ação, de modo que permita as pessoas identificarem a campanha; Orientar sobre o preenchimento de planilhas e outros materiais;

-   Definir os locais de atuação, levantar a necessidade.

::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::

## **Apresentação Pessoal**

-   É obrigatório o uso de uniforme como forma de padronizar o trabalho que será realizado;

-   Aos homens é importante apresentar-se diariamente com a barba feita;

-   Às mulheres, recomenda-se o uso moderado de maquiagem e jóias/bijuterias, que deverá ser discreta; e não esquecer o cuidado em prender cabelos longos;

-   É recomendado um cuidado redobrado com a higiene pessoal;

-   É indispensável o cuidado para não fumar, nem beber, antes da realização da ação, em virtude de fazermos parte de um programa de educação que veicula comportamento seguro e qualidade de vida;

-   Durante os trabalhos na via evitar o uso de aparelhos celular ou ficar conversando em grupos na margem da via;

-   Evitar tirar fotos com celular de condutores ou passageiros, pois será designado uma pessoa da equipe para tal função.

::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::

## **Abordagem Educativa - Parte1**

-   A maneira de abordar é fundamental para dar credibilidade a ação, devendo ser objetivo na mensagem a que se pretenda repassar; Sempre deveremos utilizar crachá, chamar as pessoas de Sr. ou Sr.ª, cumprimentar com bom dia, boa tarde ou boa noite, identificar-se como integrante da equipe de educação de trânsito;

-   A abordagem não pode ter caráter crítico ou repreensivo, deverá "conquistar", "sensibilizar" e "promover" a ideia de um comportamento seguro e valorização da vida;

-   Importante lembrar que estaremos abordando pessoas que se encontram a passeio, e que por isso poderão mostrar-se resistentes a orientações, assim deve se treinar as abordagens;

-   Para as abordagens cada integrante da equipe deverá conhecer o material a ser utilizado e tirar as dúvidas antes da ação;

-   Os membros da equipe de educação deverão posicionar-se às margens da via, sempre do lado do carona;

::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::

## **Abordagem Educativa - Parte2**

-   Em hipótese alguma deve-se "encostar" no veículo a ser abordado ou colocar a mão como forma de apoio;

-   A ordem de parada e o balizamento dos veículos deverá ser efetuada pelo Agente de Trânsito, que dará instruções à equipe visando a segurança na via;

-   Em cada abordagem deve-se observar as condutas inadequadas e orientar para a correção no momento da parada;

-   Para as condutas corretas elogiar o condutor e passageiros;

-   Toda orientação deve ser cuidadosa como forma de estimular o bom comportamento no trânsito, com o cumprimento das normas de circulação e a observância dos valores essenciais para uma boa educação no trânsito;

-   É imprescindível a comunicação entre a equipe durante as abordagens. Todos devem observar o andamento da ação e tudo que vier a ocorrer, que fuja do planejado, deverá ser comunicado imediatamente ao coordenador;

-   O atendimento da imprensa ou de repórteres de mídia alternativa devera ser feito somente pelo coordenador da ação.

::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::
